# Описание:
# - Тег релиза может иметь вид: 1.1, v1.1, v.1.1 (проверить для трех чисел) (можно добавить и другие префиксы, помимо "v" и "v." которые будут отсекаться)
# - Имя репозитория может не совпадать с именем аддона (под именем аддона здесь имеется в виду имя папки и toc-файла аддона)
# - В репозитории обязана быть папка src и в ней обязан быть один (и только один) toc-файл
# - Имя архива - это имя репозитория + символ минус + номер версии без префикса

name: Package Addon Release

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set environment variables
        run: |
          # Получить имя репозитория
          REPO_NAME="${{ github.event.repository.name }}"

          # Получить имя аддона (по имени toc-файла)
          ADDON_NAME="$(basename src/*.toc .toc)"

          # Получить версию релиза (удалив префиксы "v." и "v" из тега релиза)
          RELEASE_VERSION="${{ github.ref_name }}"
          RELEASE_VERSION="${RELEASE_VERSION#v.}"
          RELEASE_VERSION="${RELEASE_VERSION#v}"

          # Установить переменные окружения
          echo "REPO_NAME=$REPO_NAME" >> $GITHUB_ENV
          echo "ADDON_NAME=$ADDON_NAME" >> $GITHUB_ENV
          echo "RELEASE_VERSION=$RELEASE_VERSION" >> $GITHUB_ENV

      - name: Create release folder and copy files
        run: |
          cp -r src/. "$ADDON_NAME"

      - name: Process files
        run: |
          # Set release version in TOC file
          sed -i "s/_RELEASE_VERSION_/${RELEASE_VERSION}/g" "$ADDON_NAME/$ADDON_NAME.toc"

          # Remove comments and blank lines from LUA files
          find "$ADDON_NAME" -type f -name "*.lua" -exec perl -0777 -i -pe '
            # 1. Удаляем блочные комментарии, убирая только горизонтальные пробелы/табы перед --[[
            s/[ \t]*--\[\[.*?\]\]//gs;
            # 2. Удаляем однострочные комментарии с горизонтальными пробелами/табами перед --
            s/[ \t]*--.*$//gm;
            # 3. Удаляем пустые строки (включая Windows \r\n)
            s/^\s*\r?\n//gm;
            # 4. Удаляем пробелы/табы в конце строк
            s/[ \t]+$//gm;
          ' {} +

      - name: Create ZIP archive
        run: |
          zip -r "${REPO_NAME}-${RELEASE_VERSION}.zip" "${ADDON_NAME}"

      - name: Upload ZIP to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: "${REPO_NAME}-${RELEASE_VERSION}.zip"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
